name: 'Node'

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛬
        uses: actions/checkout@v4
      - name: Setup Node ⚙️
        uses: ./.github/actions/setup-node
        with:
          version: 24.x
          npm_token: ${{ secrets.NPM_TOKEN }}
      - name: Build typescript 📦
        run: yarn build && find dist/index.js
      - name: Lint code 💅
        run: yarn lint
      - name: Run tests ✅
        run: yarn test
